<?php require_once __DIR__ . '/../layouts/header.phtml' ?>
<?php if (isset($_SESSION['task'])): ?>
    <div class="alert alert-danger"><?= $_SESSION['task'] ?></div>
    <?php unset($_SESSION['task']); endif; ?>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <table class="table table-striped table-bordered table-responsive-lg">
                    <thead>
                    <tr>
                        <th>Сортировка</th>
                        <th colspan="4">
                            <a href="/?page=<?= $params['page'] ?>&sort=<?= 1 ?>">Email &uarr;</a>
                            <a href="/?page=<?= $params['page'] ?>&sort=<?= 2 ?>">Email &darr;</a>
                            <a href="/?page=<?= $params['page'] ?>&sort=<?= 3 ?>">Имя пользователя &uarr;</a>
                            <a href="/?page=<?= $params['page'] ?>&sort=<?= 4 ?>">Имя пользователя &darr;</a>
                            <a href="/?page=<?= $params['page'] ?>&sort=<?= 5 ?>">Статус &uarr;</a>
                            <a href="/?page=<?= $params['page'] ?>&sort=<?= 6 ?>">Статус &darr;</a>
                        </th>
                    </tr>
                    <tr>
                        <th>Имя пользователя</th>
                        <th>Email</th>
                        <th>Текст задачи</th>
                        <th>Статус</th>
                        <?php if (isset($_SESSION['id'])): ?>
                            <th>Действия</th>
                        <?php endif; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($params['task'] as $task): ?>
                        <tr>
                            <td>
                                <p><?= $task['name'] ?></p>
                            </td>
                            <td>
                                <p><?= $task['email'] ?></p>
                            </td>
                            <td>
                                <p class="test"><?= $task['note'] ?></p>
                                <?php if ($task['status_update']): ?>
                                    <p class="edit">Отредактировано администратором</p>
                                <?php endif; ?>
                            </td>
                            <td>
                                <?php if (isset($_SESSION['id'])): ?>
                                    <form action="/task/complete" method="POST">
                                        <input type="hidden" name="_METHOD" value="PATCH">
                                        <input type="hidden" name="task[id]" value="<?= $task['id'] ?? '' ?>">
                                        <?php if ($task['status_complete']): ?>
                                            <?= "Выполнена" ?>
                                            <input type="checkbox" name="task[status_complete]" checked>
                                        <?php endif; ?>
                                        <?php if (!$task['status_complete']): ?>
                                            <?= "Не выполнена" ?>
                                            <input type="checkbox" name="task[status_complete]">
                                        <?php endif; ?>
                                        <button class="btn btn-info" name="update">Ok</button>
                                    </form>
                                <?php endif; ?>
                                <?php if (!isset($_SESSION['id'])): ?>
                                    <?php if ($task['status_complete']): ?>
                                        <?= "Выполнена" ?>
                                    <?php endif; ?>
                                    <?php if (!$task['status_complete']): ?>
                                        <?= "Не выполнена" ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </td>
                            <?php if (isset($_SESSION['id'])): ?>
                                <td>
                                    <div class="btn-group">
                                        <form action="/task/edit" method="GET">
                                            <button class="btn btn-warning" name="id" value="<?= $task['id'] ?>">
                                                Редактировать
                                            </button>
                                        </form>
                                        <form action="/task/delete" method="POST">
                                            <input type="hidden" name="_METHOD" value="DELETE">
                                            <input type="hidden" name="task[id]" value="<?= $task['id'] ?? '' ?>">
                                            <button class="btn btn-danger" name="delete">Удалить</button>
                                        </form>
                                    </div>
                                </td>
                            <?php endif; ?>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
        <?php if ($params['countPage'] > 1): ?>
            <nav aria-label="Page navigation example ">
                <ul class="pagination justify-content-center">
                    <?php if ($params['page'] > 1): ?>
                        <li class="page-item">
                            <a class="page-link" aria-label="Previous"
                               href="/?page=<?= $params['page'] > 2 ? $params['page'] - 1 : 1 ?>&sort=<?= $params['sort'] ?? 0 ?>">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    <?php endif; ?>
                    <?php for ($i = 1; $i <= $params['countPage']; $i++): ?>
                        <li class="page-item"><a class="page-link"
                                                 href="/?page=<?= $i ?>&sort=<?= $params['sort'] ?? 0 ?>"><?= $i ?></a>
                        </li>
                    <?php endfor; ?>
                    <?php if ($params['page'] < $params['countPage']): ?>
                        <li class="page-item">
                            <a class="page-link" aria-label="Next"
                               href="/?page=<?= $params['page'] + 1 ?>&sort=<?= $params['sort'] ?? 0 ?>">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span></a>
                        </li>
                    <?php endif; ?>
                </ul>
            </nav>
        <?php endif; ?>
    </div>
<?php require_once __DIR__ . '/../layouts/footer.phtml' ?>