<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../../public/css/style.css">
</head>
<body>

<nav role="navigation" class="navbar navbar-dark bg-dark row justify-content-end">
    <div class="container-fluid justify-content-end">
        <ul class="nav">
            <a class="nav-link" href="/task/create">Добавить задачу</a>
            <?php if (!isset($_SESSION['id'])): ?>
                <li class="nav-item"><a class="nav-link" href="/admin/login">Войти</a></li>
            <?php endif; ?>
            <?php if (isset($_SESSION['id'])): ?>
                <li class="nav-item"><a class="nav-link" href="/admin/logout">Выйти</a></li>
            <?php endif; ?>
        </ul>
    </div>
</nav>

